" Internal settings
set encoding=utf-8

" Visual settings
set background=dark
set number
set autochdir

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

" let Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Let Vim load indentation rules and plugins according to the detected filetype
if has("autocmd")
  filetype plugin indent on
endif

" Show row and column number on bottom right
set ruler

" Enable syntax highlighting
syntax on
