# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/anrichter/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export PATH=$PATH:/home/anrichter/.local/bin

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git history-substring-search)

source $ZSH/oh-my-zsh.sh

# Oh My Posh
eval "$(oh-my-posh init zsh --config ~/.anrichter.omp.json)"

# directory listings
alias l='ls -lh'
alias ll='ls -alFh'
