# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/anrichter/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# directory listings
alias l='ls -l'
alias la='ls -A'
alias ll='ls -alF'
